Swallowing stderr when ignore_err is used in utility.
Also passing an extra argument to EnvironmentError since
it displays as follows:

>>> raise EnvironmentError('Commit range in unexpected format', 'a...b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
EnvironmentError: [Errno Commit range in unexpected format] a...b
>>> raise EnvironmentError(ValueError('too many values to unpack'),
...                        'Commit range in unexpected format', 'a...b')
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
EnvironmentError: [Errno too many values to unpack] Commit range in unexpected format: 'a...b'